//! Where this binary came from.
//!
//! The constant is generated by `build.rs` into `OUT_DIR` and included here
//! rather than read with `env!`, because `env!` expands in the crate where it
//! is written and `build-kit` is a different crate.

include!(concat!(env!("OUT_DIR"), "/build_stamp.rs"));

use build_kit::{Install, Stamp};

/// The libraries this binary is made of, each reporting its own version.
/// They release separately, and `farmers-api` is the one that breaks when the
/// storefront changes.
const LIBRARIES: [(&str, &str); 4] = [
    ("cli-kit", cli_kit::VERSION),
    ("net-kit", net_kit::VERSION),
    ("farmers-api", farmers_api::VERSION),
    ("build-kit", build_kit::VERSION),
];

pub fn stamp() -> &'static Stamp {
    &STAMP
}

/// `0.1.0 (abc1234 2026-01-01)` -- what `-V` prints.
///
/// Leaked once rather than rebuilt per call: clap wants a `&'static str`, and
/// a version string that lives as long as the process is not a leak worth
/// worrying about.
pub fn short_version() -> &'static str {
    static TEXT: std::sync::OnceLock<String> = std::sync::OnceLock::new();
    TEXT.get_or_init(|| STAMP.short_version()).as_str()
}

/// `--version`: the whole provenance, plus the libraries and how this file got
/// where it is.
pub fn long_version() -> &'static str {
    static TEXT: std::sync::OnceLock<String> = std::sync::OnceLock::new();
    TEXT.get_or_init(|| {
        let path = build_kit::exe_path();
        // The install record lives under the state directory, which the
        // environment can move -- so this has to resolve it the same way the
        // rest of the program does.
        let install = state_dir().and_then(|paths| Install::current(&paths));
        let note = install.as_ref().map(|i| i.note("farmers"));
        let mut text = STAMP.long_version(path.as_deref().and_then(|p| p.to_str()), note.as_ref());
        let width = LIBRARIES.iter().map(|(n, _)| n.len()).max().unwrap_or(0);
        for (i, (name, version)) in LIBRARIES.iter().enumerate() {
            let label = if i == 0 { "libraries" } else { "" };
            text.push_str(&format!("\n{label:<11}{name:<width$}  {version}"));
        }
        text
    })
    .as_str()
}

fn state_dir() -> Option<net_kit::Paths> {
    let env = crate::env::Overrides::get();
    let mut paths = net_kit::Paths::defaults(crate::app::APP).ok()?;
    if let Some(dir) = &env.state_dir {
        paths = paths.with_state_dir(dir.clone());
    }
    Some(paths)
}
